apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    {{- if .Values.datadog.enabled }}
    {{- with .Values.datadog.tags }}
    tags.datadoghq.com/env: {{ .env | quote }}
    tags.datadoghq.com/service: {{ .service | quote }}
    tags.datadoghq.com/version: {{ .version | quote }}
    {{- end }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
